# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import key_pb2 as key__pb2


class TokenStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.generate = channel.unary_unary(
        '/Token/generate',
        request_serializer=key__pb2.TokenRequest.SerializeToString,
        response_deserializer=key__pb2.TokenResponse.FromString,
        )


class TokenServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def generate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TokenServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'generate': grpc.unary_unary_rpc_method_handler(
          servicer.generate,
          request_deserializer=key__pb2.TokenRequest.FromString,
          response_serializer=key__pb2.TokenResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Token', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
